name: app-CI-PullRequest(master)

on:
  pull_request:
    branches: [ master ]
    paths:
    - 'resources/**'
    - 'lib/**/*.ts'
    - 'cdk.json'

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"

    - name: Setup dependencies
      run: |
        cd infrastructure
        pwd
        npm ci

    - name: Build
      run: |
        cd infrastructure
        npm run build

    - name: CDK Diff Check
      if: contains(github.event_name, 'pull_request')
      run: |
        cd infrastructure
        npm run cdkdiff:stg
      env:
        ENV: 'stg'
        AWS_DEFAULT_REGION: 'ap-northeast-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_TEST_DEV_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_TEST_DEV_SECRET }}

    - name: Slack Notification
      if: success()
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_USERNAME: 'Github Action - feature-push'
        SLACK_MESSAGE: ':+1: Push Success'
        SLACK_COLOR: 'good'
        SLACK_WEBHOOK: ${{ secrets.CDK_TEST_SLACK_WEBHOOK }}

    - name: Slack Notification
      if: failure()
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_USERNAME: 'Github Action - feature-push'
        SLACK_MESSAGE: ':x: Push Failure'
        SLACK_COLOR: 'danger'
        SLACK_WEBHOOK: ${{ secrets.CDK_TEST_SLACK_WEBHOOK }}
