name: app-CI-Push(master)

on:
  push:
    branches: [ master ]
    paths:
    - 'resources/**'
    - 'lib/**/*.ts'
    - 'cdk.json'

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"

    - name: Setup dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: CDK Deploy
      if: contains(github.event_name, 'push')
      run: npm run deploy:stg
      env:
        ENV: 'stg'
        AWS_DEFAULT_REGION: 'ap-northeast-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_TEST_DEV_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_TEST_DEV_SECRET }}

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_WEBHOOK: ${{ secrets.CDK_TEST_SLACK_WEBHOOK }}
